# Generated by Django 3.1.1 on 2020-09-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=128)),
                ('tank_height', models.BigIntegerField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('user_id', models.BigIntegerField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.BigIntegerField(max_length=128)),
            ],
        ),
    ]
